# Generated by Django 3.1 on 2020-08-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='items',
            new_name='item',
        ),
    ]
